# Linear Algebra

In [1]:
import numpy as np
import math

## Scalar

A scalar is a single number.

In [2]:
some_scalar = 5

## Vector

A vector is an array of numbers, arranged in an order along a dimension. Elements of a vector are identified by their corresponding subscripts, and are zero-indexed in most programming languages.

In [3]:
some_vector = [1, 2, 3]

## Matrix

A matrix is a two-dimensional array of numbers, where each element is identified by two dimensions instead of one. In most programming languages, a matrix can be defined as a "vector" of vectors with equal dimension.

In [4]:
some_matrix = [[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]]

## Tensor

A tensor is a multi (>2) dimensional array, where each element is identified by three or more dimesions. 

In [5]:
some_tensor = [[[1, 2], [3, 4]],
               [[5, 6], [7, 8]]]

## Transpose of a matrix

The transpose of a matrix is the matrix with its axes switched, i.e. the horizontal axis becomes the vertical and vice-versa, or the matrix mirrored along its diagonal

In [6]:
old_matrix = [[1, 2],
              [3, 4],
              [5, 6]]

np.transpose(old_matrix)

array([[1, 3, 5],
       [2, 4, 6]])

## Adding and multiplying scalars and matrices

When adding/multiplying scalars and matrices, the operation is performed over each and every element of the matrix (or a vector)

In [7]:
rix = np.array([[1, 2],
       [3, 4],
       [5, 6]])
3*rix + 4

array([[ 7, 10],
       [13, 16],
       [19, 22]])

## Multiplying matrices and vectors

2 matrices (or vectors) A and B can be multiplied on the following condition that **if A has dimensions (m, n) then B must have dimensions (n, p) where m may or may not equal p.** The product A x B has dimensions **(m, p)**.

In [8]:
mat1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

mat2 = np.array([[1, 2],
                [3, 4],
                [5, 6]])

np.matmul(mat1, mat2)

array([[22, 28],
       [49, 64]])

Matrices can also be multiplied element-wise. The **dot product** of A and B is denoted by **A.B** and can be defined as the product of the corresponding elements of A with B. **A and B must be of the same dimensions!**

In [9]:
mat1 = np.array([[1, 2],
                 [3, 4]])

mat2 = np.array([[5, 6],
                 [7, 8]])

np.multiply(mat1, mat2)

array([[ 5, 12],
       [21, 32]])

### Points to remember

* Matrix multiplication is NOT commutative.
* (AB)<sup>T</sup> = B<sup>T</sup>A<sup>T</sup> 
* If A and B are vectors, then A<sup>T</sup>B = B<sup>T</sup>A (The resulting product is a scalar)

## A system of equations

A system of linear equations can be defined by the following formula:
    
***Ax*** = ***b***
    
where ***A*** is a matrix, while ***x*** and ***b*** are vectors.

Expanding, this gives us

A<sub>1,:</sub>x = b<sub>1</sub><br />
A<sub>2,:</sub>x = b<sub>2</sub><br />
.<br />
.<br />
.<br />


### Identity and Inverse matrices

An identity matrix is a matrix that does not alter any matrix (or vector) that is multiplied by it. An identity matrix is always a square matrix, and is usually denoted by ***I***.

Therefore, for any matrix ***A***, 


***AI*** = ***IA*** = ***A***.

In [10]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

An inverse of a matrix ***A*** is denoted by ***A<sup>-1</sup>*** and is defined as the matrix which, when multiplied by ***A*** (or vice-versa), returns an identity matrix.

Therefore, for a matrix ***A***,

***AA<sup>-1</sup>*** = ***A<sup>-1</sup>A*** = ***I***

In [11]:
mat = np.array([[3, 2, 8],
       [6, 1, 9],
       [7, 8, 4]])

np.linalg.inv(mat)

array([[-0.33663366,  0.27722772,  0.04950495],
       [ 0.19306931, -0.21782178,  0.1039604 ],
       [ 0.2029703 , -0.04950495, -0.04455446]])

In [12]:
np.matmul(mat, np.linalg.inv(mat))

array([[ 1.00000000e+00, -1.66533454e-16, -5.55111512e-17],
       [ 5.55111512e-17,  1.00000000e+00, -2.08166817e-17],
       [-2.22044605e-16, -2.77555756e-16,  1.00000000e+00]])

### Analytically solving the system of equations

The system of equations can be analytically solved by using the inverse of the matrix ***A***.

***Ax*** = ***b***

***AA<sup>-1</sup>x*** = ***A<sup>-1</sup>b***

***Ix*** = ***A<sup>-1</sup>b***

***x*** = ***A<sup>-1</sup>b***

### Points to remember:

* If ***A*** is singular, then ***A<sup>-1</sup>*** does not exist. In such cases, a *pseudoinverse* may need to be calculated.

## Linear Dependence and Span

If ***A*** is not singular, then one solution exists for the system of linear equations. Similarly, if ***A*** is singular, then infinitely many, or no solutions exist for the system. Therefore, if both ***x*** and ***y*** satisfy a system of linear equations, then

***z*** = a***x*** + (1-a)***y***

is also a solution to the equation, for all real a.

### Linear Combination

The linear combination of a set of vectors {v<sup>(1)</sup>, v<sup>(2)</sup>... v<sup>(n)</sup>} is given by multiplying each vector by a corresponding scalar coefficient and adding them up.

The set of all points obtainable by linear combination of the original vectors is called the **span** of the set of vectors.

## Norms

Norms are methods used to identify the "size" of a vector, such as the magnitude of a complex number. This is achieved by adding all the elements of a vector to the p<sup>th</sup> power and then taking the p<sup>th</sup> root of the sum.

The p<sup>th</sup> norm of a vector **x** is denoted by ||**x**||<sub>p</sub>

In [13]:
def getNorm(V, p):
    # V is the vector and p is the power
    receivedSum = 0
    for v in V:
        receivedSum += math.abs(v)**p
    return receivedSum**(1/p)

All norms follow the following properties:

* f(x) = 0 implies x = 0
* f(x + y) <= f(x) + f(y)
* f(ax) = |a|f(x) for all real a

A very common norm is the L<sup>2</sup> norm, also known as the Euclidean norm. This is just the Euclidean distance from the origin to the point identified by the vector. For a vector **x**, this is denoted by **x**<sup>T</sup>**x**

Another common norm, especially in machine learning, is the L<sup>infinity</sup> norm, also known as the max norm. The value is simply the largest magnitude in the vector.

For vectors, the "size" is denoted by the **Frobenius norm**, which is the achieved by computing the L<sup>2</sup> norm of a "flattened" version of the matrix, i.e. by summing the squares of every element and getting the square root of the entire thing.

In [14]:
def getFrobeniusNorm(M):
    matrixSum = 0
    for row in M:
        for ele in row:
            matrixSum += ele**2
    return math.sqrt(matrixSum)